const quarters = [
  { value: "Canaã II", label: "Canaã II" },
  { value: "Canaã IV", label: "Canaã IV" },
  { value: "Chácara Califórnia", label: "Chácara Califórnia" },
  { value: "Jardim Alhambra", label: "Jardim Alhambra" },
  { value: "Jardim Jóquei Clube", label: "Jardim Jóquei Clube" },
  { value: "Jardim Santa Felicidade", label: "Jardim Santa Felicidade" },
  { value: "Parque das Nações II", label: "Parque das Nações II" },
  { value: "Parque Rincão I", label: "Parque Rincão I" },
  { value: "Parque Rincão II", label: "Parque Rincão II" },
  { value: "Vila Anete", label: "Vila Anete" },
  { value: "Vila Mariana", label: "Vila Mariana" },
  { value: "Vila São Braz", label: "Vila São Braz" },
  { value: "Vila Valderez", label: "Vila Valderez" },
  { value: "Jardim Brasília", label: "Jardim Brasília" },
  { value: "Jardim João Paulo II", label: "Jardim João Paulo II" },
  { value: "Jardim Márcia", label: "Jardim Márcia" },
  { value: "Jardim São Cristóvão", label: "Jardim São Cristóvão" },
  { value: "Parque das Nações I", label: "Parque das Nações I" },
  { value: "Vila Cuiabá", label: "Vila Cuiabá" },
  { value: "Vila Guarani", label: "Vila Guarani" },
  { value: "Vila Industrial", label: "Vila Industrial" },
  { value: "Vila Martins", label: "Vila Martins" },
  { value: "Vila Santa Catarina", label: "Vila Santa Catarina" },
  { value: "Vila Ubiratan", label: "Vila Ubiratan" },
  { value: "Vila Santa Clara", label: "Vila Santa Clara" },
  { value: "Vila Viegas", label: "Vila Viegas" },
  { value: "Vila Vieira", label: "Vila Vieira" },
  {
    value: "Residencial Oliveira I e II",
    label: "Residencial Oliveira I e II"
  },
  { value: "Conjunto Izidro Pedroso", label: "Conjunto Izidro Pedroso" },
  { value: "Jardim Colibri", label: "Jardim Colibri" },
  { value: "Jardim Flamboyant", label: "Jardim Flamboyant" },
  { value: "Jardim Santa Rita", label: "Jardim Santa Rita" },
  { value: "Parque dos Beija-Flores", label: "Parque dos Beija-Flores" },
  { value: "Parque dos Bem-te-vis", label: "Parque dos Bem-te-vis" },
  {
    value: "Parque dos Coqueiros I e II",
    label: "Parque dos Coqueiros I e II"
  },
  { value: "Parque dos Jequitibás", label: "Parque dos Jequitibás" },
  { value: "Parque Nova Dourados", label: "Parque Nova Dourados" },
  { value: "Terra Roxa I e II", label: "Terra Roxa I e II" },
  { value: "Vila Aimoré", label: "Vila Aimoré" },
  { value: "Jardim Del Rey", label: "Jardim Del Rey" },
  { value: "Jardim Rigotti", label: "Jardim Rigotti" },
  { value: "Jardim Santo André", label: "Jardim Santo André" },
  { value: "Jardim São Pedro", label: "Jardim São Pedro" },
  { value: "Parte do Centro (Oeste)", label: "Parte do Centro (Oeste)" },
  { value: "Vila Adelina I e II", label: "Vila Adelina I e II" },
  { value: "Vila Helena", label: "Vila Helena" },
  { value: "Vila Sulmat", label: "Vila Sulmat" },
  { value: "BNH 4º Plano", label: "BNH 4º Plano" },
  { value: "Conjunto Campo Dourado", label: "Conjunto Campo Dourado" },
  { value: "Jardim Manoel Rasselen", label: "Jardim Manoel Rasselen" },
  { value: "Jardim Vista Alegre", label: "Jardim Vista Alegre" },
  { value: "Cachoeirinha", label: "Cachoeirinha" },
  { value: "Canaã VI (Cachoeirinha)", label: "Canaã VI (Cachoeirinha)" },
  { value: "Cohab II", label: "Cohab II" },
  {
    value: "Jardim Cel. Francisco Alves",
    label: "Jardim Cel. Francisco Alves"
  },
  { value: "Jardim Clímax", label: "Jardim Clímax" },
  { value: "Jardim Cuiabazinho", label: "Jardim Cuiabazinho" },
  { value: "Jardim Independência", label: "Jardim Independência" },
  { value: "Jardim Itália", label: "Jardim Itália" },
  { value: "Jardim Londina", label: "Jardim Londina" },
  { value: "Jardim Mana", label: "Jardim Mana" },
  { value: "Jardim Maringá", label: "Jardim Maringá" },
  { value: "Jardim Mato Grosso", label: "Jardim Mato Grosso" },
  { value: "Jardim Morada do Salto", label: "Jardim Morada do Salto" },
  { value: "Mutirão da Moradia", label: "Mutirão da Moradia" },
  { value: "Parte do Centro (Leste)", label: "Parte do Centro (Leste)" },
  { value: "Vila Almeida", label: "Vila Almeida" },
  { value: "Vila Amaral", label: "Vila Amaral" },
  { value: "Vila Bela", label: "Vila Bela" },
  { value: "Vila Erondina I", label: "Vila Erondina I" },
  { value: "Vila Hilda", label: "Vila Hilda" },
  { value: "Altos do Indaiá", label: "Altos do Indaiá" },
  { value: "Jardim das Primaveras", label: "Jardim das Primaveras" },
  { value: "Jardim Flórida I", label: "Jardim Flórida I" },
  { value: "Jardim Flórida II", label: "Jardim Flórida II" },
  { value: "Jardim Novo Horizonte", label: "Jardim Novo Horizonte" },
  { value: "Jardim Olinda", label: "Jardim Olinda" },
  { value: "Panambi Verá", label: "Panambi Verá" },
  { value: "Parque do Lago I e II", label: "Parque do Lago I e II" },
  { value: "Vila Delfus", label: "Vila Delfus" },
  { value: "Vila Popular", label: "Vila Popular" },
  { value: "Alto das Palmeiras", label: "Alto das Palmeiras" },
  { value: "Bairro Jardim", label: "Bairro Jardim" },
  { value: "BNH 1º Plano", label: "BNH 1º Plano" },
  { value: "BNH 2º Plano", label: "BNH 2º Plano" },
  { value: "BNH 3º Plano", label: "BNH 3º Plano" },
  { value: "Centro", label: "Centro" },
  { value: "Chácara 38", label: "Chácara 38" },
  { value: "Chácara Flora", label: "Chácara Flora" },
  { value: "Cidade Áurea", label: "Cidade Áurea" },
  {
    value: "Conjunto Res. Monte Carlo",
    label: "Conjunto Res. Monte Carlo"
  },
  { value: "Jardim América", label: "Jardim América" },
  { value: "Jardim Apuena", label: "Jardim Apuena" },
  { value: "Jardim Bará", label: "Jardim Bará" },
  { value: "Jardim Central", label: "Jardim Central" },
  { value: "Jardim da Figueira", label: "Jardim da Figueira" },
  { value: "Jardim Europa", label: "Jardim Europa" },
  { value: "Jardim Faculdade", label: "Jardim Faculdade" },
  { value: "Jardim Girassol", label: "Jardim Girassol" },
  { value: "Jardim Itaipú", label: "Jardim Itaipú" },
  { value: "Jardim Monte Alegre", label: "Jardim Monte Alegre" },
  { value: "Jardim Pilau", label: "Jardim Pilau" },
  { value: "Jardim Tropical", label: "Jardim Tropical" },
  { value: "Jardim Universitário", label: "Jardim Universitário" },
  { value: "Jardim Valéria", label: "Jardim Valéria" },
  { value: "Jardim Zeina", label: "Jardim Zeina" },
  { value: "Parque Alvorada", label: "Parque Alvorada" },
  { value: "Portal de Dourados", label: "Portal de Dourados" },
  { value: "Prolongamento Itaipu", label: "Prolongamento Itaipu" },
  {
    value: "Residencial Valdomiro A. Monteiro",
    label: "Residencial Valdomiro A. Monteiro"
  },
  { value: "Residencial Ypacarai", label: "Residencial Ypacarai" },
  { value: "Vila Alvorada", label: "Vila Alvorada" },
  { value: "Vila Aurora", label: "Vila Aurora" },
  { value: "Vila Corumbá", label: "Vila Corumbá" },
  { value: "Vila Lili", label: "Vila Lili" },
  { value: "Vila Matos", label: "Vila Matos" },
  {
    value: "Vila Nossa Senhora Aparecida",
    label: "Vila Nossa Senhora Aparecida"
  },
  { value: "Vila Planalto", label: "Vila Planalto" },
  { value: "Vila Progresso", label: "Vila Progresso" },
  { value: "Vila Real", label: "Vila Real" },
  { value: "Vila Rui Barbosa", label: "Vila Rui Barbosa" },
  { value: "Vila Santana", label: "Vila Santana" },
  { value: "Vila São José", label: "Vila São José" },
  { value: "Vila São Luiz", label: "Vila São Luiz" },
  { value: "Vila Tonani", label: "Vila Tonani" },
  { value: "Vila Tonani I", label: "Vila Tonani I" },
  { value: "Canaã V", label: "Canaã V" },
  { value: "Jardim Caramuru", label: "Jardim Caramuru" },
  { value: "Jardim Caiman", label: "Jardim Caiman" },
  { value: "Jardim Guanabara", label: "Jardim Guanabara" },
  { value: "Jardim Guarujá", label: "Jardim Guarujá" },
  { value: "Jardim Leste", label: "Jardim Leste" },
  { value: "Jardim Maipu", label: "Jardim Maipu" },
  { value: "Jardim Marabá", label: "Jardim Marabá" },
  { value: "Jardim Maracanã", label: "Jardim Maracanã" },
  { value: "Jardim Ouro Verde", label: "Jardim Ouro Verde" },
  { value: "Jardim Paulista", label: "Jardim Paulista" },
  { value: "Jardim Santa Maria", label: "Jardim Santa Maria" },
  { value: "Vila Alba", label: "Vila Alba" },
  { value: "Vila Eldorado", label: "Vila Eldorado" },
  { value: "Vila Icassati", label: "Vila Icassati" },
  { value: "Vila Mary", label: "Vila Mary" },
  { value: "Vila Maxwel", label: "Vila Maxwel" },
  { value: "Vila Mello", label: "Vila Mello" },
  { value: "Vila Nova Esperança", label: "Vila Nova Esperança" },
  { value: "Vila Santa Hermínia", label: "Vila Santa Hermínia" },
  { value: "Vila São Francisco", label: "Vila São Francisco" },
  { value: "Altos da Monte Alegre", label: "Altos da Monte Alegre" },
  { value: "Canaã I", label: "Canaã I" },
  { value: "Chácaras Caiuás", label: "Chácaras Caiuás" },
  { value: "Jardim Aydê", label: "Jardim Aydê" },
  { value: "Jardim Carisma", label: "Jardim Carisma" },
  { value: "Jardim Coimasa", label: "Jardim Coimasa" },
  { value: "Jardim Continental", label: "Jardim Continental" },
  { value: "Jardim dos Estados", label: "Jardim dos Estados" },
  { value: "Jardim Laranja Doce", label: "Jardim Laranja Doce" },
  { value: "Jardim Marília", label: "Jardim Marília" },
  { value: "Jardim Monte Líbano", label: "Jardim Monte Líbano" },
  { value: "Jardim Murakami", label: "Jardim Murakami" },
  { value: "Jardim Piratininga", label: "Jardim Piratininga" },
  { value: "Jardim Santa Brígida", label: "Jardim Santa Brígida" },
  {
    value: "Parque Residencial Pelicano",
    label: "Parque Residencial Pelicano"
  },
  { value: "Parte Chácara", label: "Parte Chácara" },
  { value: "Vila Aracy", label: "Vila Aracy" },
  { value: "Vila Arapongas", label: "Vila Arapongas" },
  { value: "Vila Barros", label: "Vila Barros" },
  { value: "Vila Dourado", label: "Vila Dourado" },
  { value: "Vila Esperança", label: "Vila Esperança" },
  { value: "Vila Índio", label: "Vila Índio" },
  { value: "Vila Iran P. Matos", label: "Vila Iran P. Matos" },
  { value: "Vila Norte", label: "Vila Norte" },
  { value: "Vila Rosa", label: "Vila Rosa" },
  { value: "Vila São Jorge", label: "Vila São Jorge" },
  { value: "Outro", label: "Outro" }
];

export default quarters;
